[32m2023-04-25 18:34:13 +0200[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5648ea1b-1ec5-4a01-812a-95ca55d07169 - 22654 - LOGS_CAPTURED - Started capturing logs in process (pid: 22654).
[32m2023-04-25 18:34:13 +0200[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5648ea1b-1ec5-4a01-812a-95ca55d07169 - 22654 - upload_to_s3 - STEP_START - Started execution of step "upload_to_s3".
[32m2023-04-25 18:34:13 +0200[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 5648ea1b-1ec5-4a01-812a-95ca55d07169 - 22654 - upload_to_s3 - STEP_FAILURE - Execution of step "upload_to_s3" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "upload_to_s3"::

IsADirectoryError: [Errno 21] Is a directory: './realestate_scraping/data/'

Stack Trace:
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/env/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/env/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 443, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/env/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 124, in _coerce_solid_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/env/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 118, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/realestate-scraping/realestate_scraping/assets/core/realestate_scraping.py", line 139, in upload_to_s3
    s3_client.fput_object(context.resources.s3.bucket_name, filename, LOCAL_PATH)
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/env/lib/python3.11/site-packages/minio/api.py", line 991, in fput_object
    with open(file_path, "rb") as file_data:
         ^^^^^^^^^^^^^^^^^^^^^
[0m
